### ISSUE TITLE
unexpected protocol error, HTTP/000 returned

### ISSUE THREAD

**Issue by mehazkaur** [ivanra/sblookup#1]
i try the given sblookup code thro API key but the out put is 
command run:-./sblookup -a ABQIAAAA05SKfG4tLA46a2fHMP5uXxTiS8m_8J8u7ie-ne8rBb3_JokVSw example

out put:-000
sblookup: error: unexpected protocol error, HTTP/000 returned.

**Comment by ivanrad** [comment]
The error message (**HTTP/000**) indicates that there was a network connection error. Essentially, the underlying `curl` HTTP request has unexpectedly failed. It could be that your network connection was temporarily down, proxy acting up, etc.

BTW Your API key is invalid (not that you should be posting a valid key here):

```
$ echo "http://example.com" | sblookup -a <your_key>
sblookup: error: HTTP/403, possibly invalid API key.
```

**Comment by mehazkaur** [comment]
Same API key properly worked in JAVA programming and create a text file to save result.
same thing can be happen in Curl?

**Comment by mehazkaur** [comment]
when i run the above said command the output is:
echo "http://google.com" | ./sblookup -a ABQIAAAA05SKfG4tLA46a2fHMP5uXxTiS8m_8J8u7ie-ne8rBb3_JokVSw

url list     'http://google.com'
array value  http://google.com

sblookup: error: unexpected protocol error, HTTP/000 returned.

**Comment by mehazkaur** [comment]
$curl -s --write-out \n%{http_code} "http://facebook.com" 
302

this command works properly.

**Comment by ivanrad** [comment]
Try generating a new API (server) key. I'm not getting that error on my side, only HTTP/403 -- which tells me that the key is not working. Although, it could be that it had an IP whitelist attached to it when it was created, so it's not supposed to be working for me in the first place. In any case, this is the equivalent to what you're invoking above:

```
$ printf "1\nhttp://google.com" | curl -i --data-binary @- "https://sb-ssl.google.com/safebrowsing/api/lookup?client=test&appver=1&pver=3.1&key=ABQIAAAA05SKfG4tLA46a2fHMP5uXxTiS8m_8J8u7ie-ne8rBb3_JokVSw"
HTTP/1.1 403 Forbidden
Content-Type: application/octet-stream
X-Content-Type-Options: nosniff
Server: HTTP server (unknown)
Content-Length: 0
X-Frame-Options: SAMEORIGIN
...
```

As you can see, the API is returning HTTP/403.

**Comment by mehazkaur** [comment]
thanks for reply.
please tell me steps to generate server API key.

**Comment by mehazkaur** [comment]
when i run this command-
 curl https://google.com
output is :-
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). The default
 bundle is named curl-ca-bundle.crt; you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

Is it also related to this issue? 
one more thing i am using linux on sharing basis.
please reply soon.

**Comment by mehazkaur** [comment]
now SSL certificate issue resolved and when i run this command
 curl -s -k --write-out \n%{http_code} https://sb-ssl.google.com/safebrowsing/api/lookup?client=api&apikey=ABQIAAAA05SKfG4tLA46a2fHMP5uXxTiS8m_8J8u7ie-ne8rBb3_JokVSw&appver=1.5.2&pver=3.0&url=http%3A%2F%2Fscottlinux.com
output is:
[1] 21032
[2] 21033
[3] 21034
[4] 21035
[root@www sarb]#
400
tell me whats the reason

**Comment by ivanrad** [comment]
You are missing some quotes there. Here you go:

```
$ curl -s -k --write-out "\n%{http_code}" "https://sb-ssl.google.com/safebrowsing/api/lookup?client=api&apikey=ABQIAAAA05SKfG4tLA46a2fHMP5uXxTiS8m_8J8u7ie-ne8rBb3_JokVSw&appver=1.5.2&pver=3.0&url=http%3A%2F%2Fscottlinux.com"

204
```

**Comment by mehazkaur** [comment]
Thanks. Thanks A lot.

**Comment by mehazkaur** [comment]
how to resolve that problem in sblookup script

sblookup_url="https://sb-ssl.google.com/safebrowsing/api/lookup?client=sblookup&appver=${version_info}&pver=3.1&apikey="
curl_cmd="curl -s -k --write-out \n%{http_code} @- "

**Comment by ivanrad** [comment]
You can force `curl` to skip SSL certification validation -- by using the `-k/--insecure` flag (e.g. by adding it to you `.curlrc`), but you would be better off fixing the underlying problem on your box, by installing a proper CA cert bundle. See the `curl` output you pasted above for instructions (i.e. read [this document](http://curl.haxx.se/docs/sslcerts.html)).

**Comment by mehazkaur** [comment]
please tell me steps to set CA certification path

**Comment by ivanrad** [comment]
Sorry, that's just beyond the scope... The steps are described in the link I've sent you above, which is the same as the link that shows up in your `curl` error message ([cURL SSL CA certificates](http://curl.haxx.se/docs/sslcerts.html)).

**Comment by mehazkaur** [comment]
ok.
