### ISSUE TITLE
Trailing slash matters in checked URL

### ISSUE THREAD

**Issue by slrslr** [ivanra/sblookup#3]
Hello,

it is not mentioned in the README.md, note this:

domain.tld - OK
http://domain.tld - OK
http://domain.tld/deceptivesitedir - OK
http://domain.tld/deceptivesitedir/ - phishing

So one have to test directories and use trailing slash too....!

**Comment by ivanrad** [comment]
Hi.

The URL is passed **as-is** to the Safe Browsing Lookup API, which in turns renders the verdict. The script will not change (canonicalize/encode) the URLs in any way. That said, I don't believe a trailing slash is always necessary in the path segment for the API to detect it as a malicious URL, I think it may vary on a case by case basis. For example:

```
echo -e "http://sceper.ws/page/2\nhttp://sceper.ws/page/2/" | sblookup
phishing        http://sceper.ws/page/2
phishing        http://sceper.ws/page/2/
```

As you may have noticed, this tool, old as it is, is now targeting legacy **v3** version of the Safe Browsing Lookup API. It may be time to think about `sblookup2`, which can make use of the current, **v4** API.

**Comment by slrslr** [comment]
thx, so it seems better is to use trailing slash. I was not aware there is any sblookup2 and i can not find it

**Comment by ivanrad** [comment]
There is no `sblookup2`. It might be time to think about writing one. :smile:
